version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: asy_storage
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-cryptography}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
